name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run a test
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. && make -j8 && ./leetcode
          
      
